CREATE TABLE "audit_runs" (
	"id" text PRIMARY KEY NOT NULL,
	"user_id" text,
	"algorithm_version" text DEFAULT '1.7',
	"status" "AuditStatus" DEFAULT 'PENDING',
	"start_date" timestamp,
	"end_date" timestamp,
	"total_events" integer,
	"total_hours" double precision,
	"unique_hours" double precision,
	"founder_hours" double precision,
	"senior_hours" double precision,
	"junior_hours" double precision,
	"ea_hours" double precision,
	"planning_score" double precision,
	"annual_loss" double precision,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp,
	"completed_at" timestamp,
	"calendars_included" text[],
	"exclusions_used" text[],
	"computed_metrics" jsonb,
	"planning_assessment" text,
	"leave_days_detected" integer DEFAULT 0,
	"leave_hours_excluded" numeric DEFAULT '0',
	"frequency" text DEFAULT 'manual'
);
--> statement-breakpoint
CREATE TABLE "events" (
	"id" text PRIMARY KEY NOT NULL,
	"audit_run_id" text,
	"external_id" text,
	"title" text,
	"description" text,
	"start_time" timestamp,
	"end_time" timestamp,
	"duration_minutes" integer,
	"tier" "EventTier",
	"tier_confidence" double precision,
	"is_manual_override" boolean DEFAULT false,
	"attendee_count" integer DEFAULT 0,
	"is_recurring" boolean DEFAULT false,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp,
	"is_all_day" boolean DEFAULT false,
	"calendar_id" text,
	"has_meet_link" boolean DEFAULT false,
	"suggested_tier" text,
	"business_area" text,
	"vertical" text,
	"confidence_score" text,
	"keywords_matched" text[],
	"is_leave" boolean DEFAULT false,
	"leave_detection_method" text,
	"leave_confidence" text,
	"planning_score" integer
);
--> statement-breakpoint
ALTER TABLE "audit_runs" ADD CONSTRAINT "audit_runs_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "events" ADD CONSTRAINT "events_audit_run_id_audit_runs_id_fk" FOREIGN KEY ("audit_run_id") REFERENCES "public"."audit_runs"("id") ON DELETE cascade ON UPDATE no action;